# Generated by Django 5.1.2 on 2025-10-31 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_timestamp_logentry_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='last_produced',
        ),
        migrations.AddField(
            model_name='topic',
            name='replications',
            field=models.PositiveBigIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='topic',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
