# Generated by Django 5.1.2 on 2025-10-31 10:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_topic_last_produced_topic_replications_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='replications',
        ),
        migrations.AddField(
            model_name='topic',
            name='last_produced',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
