# Generated by Django 5.1.2 on 2025-11-04 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_topic_replications_topic_last_produced_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='replications',
            field=models.IntegerField(default=3),
        ),
    ]
