# Generated by Django 5.1.2 on 2025-11-06 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_topic_replications'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicrequest',
            name='request_type',
            field=models.CharField(choices=[('creation', 'Creation'), ('deletion', 'Deletion')], default='creation', max_length=20),
        ),
    ]
