# Generated by Django 5.1.2 on 2025-12-16 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_topicrequest_request_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topicrequest',
            old_name='requested_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='topicrequest',
            name='partitions',
        ),
        migrations.RemoveField(
            model_name='topicrequest',
            name='reviewed_at',
        ),
        migrations.RemoveField(
            model_name='topicrequest',
            name='reviewed_by',
        ),
        migrations.AddField(
            model_name='topicrequest',
            name='new_partitions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topicrequest',
            name='new_replication_factor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topicrequest',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.topic'),
        ),
        migrations.AlterField(
            model_name='topicrequest',
            name='request_type',
            field=models.CharField(choices=[('CREATE', 'Create'), ('DELETE', 'Delete'), ('ALTER', 'Alter')], max_length=10),
        ),
        migrations.AlterField(
            model_name='topicrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined')], default='PENDING', max_length=10),
        ),
    ]
