# Generated by Django 5.1.2 on 2025-12-23 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_requested_at_topicrequest_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicrequest',
            name='decline_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
